[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "1h"

[".config/bat/themes/Catppuccin-Mocha.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "168h"
# bat cache --build
