[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "168h"

[".config/bat/themes"]
type = "archive"
url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
exact = true
stripComponents = 2
refreshPeriod = "168h"
include = ["*/themes/**"]
# bat cache --build

[".config/atuin/themes"]
type = "archive"
url = "https://github.com/catppuccin/atuin/archive/main.tar.gz"
exact = true
stripComponents = 3
refreshPeriod = "168h"
include = ["*/themes/**"]

[".bash-preexec.sh"]
type = "file"
url = "https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh"
refreshPeriod = "168h"
